# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Weijian Duan
email: weijianduan0302@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  想象个人与公共生活另一种可能
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WeijianDuan
github_username: weijianduan0302

# Build settings
# [removed] theme: minima
plugins:
  - jekyll-feed

# Feed 设置
feed:
  posts_limit: 20 # 限制每个 feed 最多显示的条目
  collections:
    - tweets # 添加 tweets 集合到 feed 中
  tags: true # 如果你想为标签生成单独的 feed

# 为不同类型的内容创建单独的 feed
jekyll-feed:
  - path: feed_all.xml # 默认 feed，包含所有内容
    title: 全部内容
  - path: feed_blog.xml # 仅博客文章
    title: 博客文章
    posts_limit: 20
    categories:
      - posts
  - path: feed_tweet.xml # 仅碎碎念
    title: 碎碎念
    posts_limit: 20
    collections:
      - tweets

header_pages:
  - nav_tweets.markdown
  - nav_blog.markdown
  - nav_about.markdown
  - nav_rss.markdown

collections:
  tweets:
    output: true
    permalink: /tweets/:year/:month/:day/:hour:minute/

# Jekyll Compose 默认设置
jekyll_compose:
  auto_open: true
  default_front_matter:
    # 碎碎念的默认 front matter
    tweets:
      layout: tweet

